# CREATE SCHEMA auction;

CREATE TABLE auction.CARD
(
    CARD_ID INT AUTO_INCREMENT PRIMARY KEY,
    CVC     CHAR(3)  NOT NULL,
    NUMBER  CHAR(16) NOT NULL,
    VALID   CHAR(5)  NOT NULL
);

CREATE TABLE auction.SUBCATEGORY
(
    SUBCATEGORY_ID   INT AUTO_INCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE auction.CATEGORY
(
    CATEGORY_ID   INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE auction.CATEGORY_SUBCATEGORY
(
    CATEGORY_SUBCATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_ID             INT NOT NULL,
    SUBCATEGORY_ID          INT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES auction.CATEGORY (CATEGORY_ID),
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES auction.SUBCATEGORY (SUBCATEGORY_ID)
);

CREATE TABLE auction.NEWS
(
    NEWS_ID          INT AUTO_INCREMENT PRIMARY KEY,
    NEWS_HEADER      VARCHAR(50) NOT NULL,
    NEWS_DESCRIPTION VARCHAR(500),
    PICTURE          LONGBLOB
);
CREATE TABLE auction.USER
(
    USER_ID    INT AUTO_INCREMENT PRIMARY KEY,
    MAIL       VARCHAR(30) UNIQUE NOT NULL,
    USERNAME   VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(20)        NOT NULL,
    CITY       VARCHAR(40),
    TOKEN      VARCHAR(100),
    USER_CARD  INT,
    PATRONYMIC VARCHAR(40),
    SURNAME    VARCHAR(40),
    NAME       VARCHAR(40),
    COUNTRY    VARCHAR(3),
    PHONE      VARCHAR(40) UNIQUE,
    AVATAR     LONGBLOB,
    RATING     INT                NOT NULL DEFAULT 0,
    PROFILE    VARCHAR(10)                 DEFAULT 'BUSINESS',
    FOREIGN KEY (USER_CARD) REFERENCES auction.CARD (CARD_ID)
);
CREATE TABLE auction.LOT
(
    LOT_ID            INT AUTO_INCREMENT PRIMARY KEY,
    OWNER_ID          INT         NOT NULL,
    CATEGORY_ID       INT         NOT NULL,
    SUBCATEGORY_ID    INT,
    NAME              VARCHAR(30) NOT NULL,
    STEP              INT         NOT NULL,
    MIN_PRICE         INT         NOT NULL,
    DATE_OF_PUT       DATETIME    NOT NULL,
    SELL_DATE         DATE        NOT NULL,
    FILTER            VARCHAR(30),
    DEAL_TYPE         varchar(15) NOT NULL,
    STATE             TINYINT     NOT NULL,
    COUNTRY           CHAR(3),
    PRICE_FOR_SELLING INT,
    IS_APPROVED       BOOL        NULL,
    DESCRIPTION       VARCHAR(255),
    FOREIGN KEY (OWNER_ID) REFERENCES auction.USER (USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES auction.CATEGORY (CATEGORY_ID),
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES auction.SUBCATEGORY (SUBCATEGORY_ID)
);

CREATE TABLE auction.PICTURES
(
    PICTURE_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOT_ID     INT      NOT NULL,
    PICTURE    LONGBLOB NOT NULL,
    FOREIGN KEY (LOT_ID) REFERENCES LOT (LOT_ID)
);

CREATE TABLE auction.TRACKING_SYSTEM
(
    TRACKING_SYSTEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID            INT NOT NULL,
    LOT_ID             INT NOT NULL,
    FOREIGN KEY (LOT_ID) REFERENCES LOT (LOT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

CREATE TABLE auction.FACT_SALE
(
    FACT_SALE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID      INT      NOT NULL,
    LOT_ID       INT      NOT NULL,
    SALE_TIME    DATETIME NOT NULL,
    PRICE        INT      NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES auction.USER (USER_ID),
    FOREIGN KEY (LOT_ID) REFERENCES auction.LOT (LOT_ID)
);
CREATE TABLE auction.FACT_OVERRIDE
(
    FACT_OVERRIDE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID          INT      NOT NULL,
    LOT_ID           INT      NOT NULL,
    OVERRIDE_TIME    DATETIME NOT NULL,
    PRICE            INT      NOT NULL,
    FOREIGN KEY (LOT_ID) REFERENCES auction.LOT (LOT_ID),
    FOREIGN KEY (USER_ID) REFERENCES auction.USER (USER_ID)
);

CREATE TABLE auction.MESSAGE
(
    MESSAGE_ID   INT AUTO_INCREMENT PRIMARY KEY,
    TEXT         VARCHAR(255) NOT NULL,
    FROM_USER    INT          NOT NULL,
    TO_USER      INT          NOT NULL,
    MESSAGE_DATE TIMESTAMP    NOT NULL,
    FOREIGN KEY (FROM_USER) REFERENCES auction.USER (USER_ID),
    FOREIGN KEY (TO_USER) REFERENCES auction.USER (USER_ID)
);
